spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
#  cloud:
#    openfeign:
##      oauth2:
##        enabled: true
##        clientRegistrationId: cityGuide
#      client:
#        config:
#          google-api:               # annotated by @FeignClient(name = "google-api") in interface GoogleApiClient
#            url: https://routes.googleapis.com/directions/v2:computeRoutes
#            loggerLevel: basic       # clickIn - choices are FULL, HEADER, BASIC, NONE
##            default-request-headers:

  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/cityguide
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATBASE_PASSWORD:cityguide123789}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:database-init.sql"

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: TRACE # Incoming HTTP requests
    org.springframework.jdbc.datasource.init: DEBUG # Database initialization
    org.springframework.jdbc.core: DEBUG # SQL