version: '3.8'

services:

  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: cityguide
      POSTGRES_PASSWORD: cityguide123789
    volumes:
      - cityguide-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  cityguide-pg-local: